name: Create release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  create:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
    steps:
      - name: Create release
        id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build:
    name: ${{ matrix.os }}-hosted
    needs: create
    env:
      buildDir: '${{ github.workspace }}/build'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
        exclude:
        - os: windows-latest
          arch: arm64
        - os: ubuntu-latest
          arch: arm64
    steps:
      - name: Checks-out
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19.2'
      - run: make arch-${{ matrix.arch }}
      - name: Compress
        uses: papeloto/action-zip@v1
        with:
          files: build/${{ matrix.arch }}
          dest: ${{ github.event.repository.name }}-${{ runner.os }}-${{ matrix.arch }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}-${{ runner.os }}-${{ matrix.arch }}.zip